// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjNRB_iehIgKMbeiDc9R6TfEj61FAqKqI',
    appId: '1:847759289282:web:68f9d461cbfd531b77845b',
    messagingSenderId: '847759289282',
    projectId: 'flutter-template-3887d',
    authDomain: 'flutter-template-3887d.firebaseapp.com',
    storageBucket: 'flutter-template-3887d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjNRB_iehIgKMbeiDc9R6TfEj61FAqKqI',
    appId: '1:847759289282:android:68f9d461cbfd531b77845b',
    messagingSenderId: '847759289282',
    projectId: 'flutter-template-3887d',
    storageBucket: 'flutter-template-3887d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjNRB_iehIgKMbeiDc9R6TfEj61FAqKqI',
    appId: '1:847759289282:ios:68f9d461cbfd531b77845b',
    messagingSenderId: '847759289282',
    projectId: 'flutter-template-3887d',
    storageBucket: 'flutter-template-3887d.firebasestorage.app',
    iosBundleId: 'com.tmc.fluttertemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjNRB_iehIgKMbeiDc9R6TfEj61FAqKqI',
    appId: '1:847759289282:ios:68f9d461cbfd531b77845b',
    messagingSenderId: '847759289282',
    projectId: 'flutter-template-3887d',
    storageBucket: 'flutter-template-3887d.firebasestorage.app',
    iosBundleId: 'com.tmc.fluttertemplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjNRB_iehIgKMbeiDc9R6TfEj61FAqKqI',
    appId: '1:847759289282:web:68f9d461cbfd531b77845b',
    messagingSenderId: '847759289282',
    projectId: 'flutter-template-3887d',
    authDomain: 'flutter-template-3887d.firebaseapp.com',
    storageBucket: 'flutter-template-3887d.firebasestorage.app',
  );
}
